name: "CCT SCADA"
version: "0.0.32"
slug: "cct_dp3_scada"
description: "Home Assistant add-on CoCT DNP3"
url: "https://github.com/Voyanti/dnp3-scadat-test"
init: false
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
host_network: true

options:
  server: "vpn.example.com"
  OUTSTATION_ADDR: 101
  LISTEN_IP: "0.0.0.0"
  event_buffer_size: 20
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: mqtt-user
  mqtt_password: mqtt-user
  mqtt_base_topic: "scada"
  plant_ac_generated_topic: "test/plant"
  grid_reactive_topic: "test/reactive"
  grid_export_topic: "test/export"

schema:
  server: str
  outstation_addr: int
  listen_ip: str
  event_buffer_size: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  mqtt_base_topic: str
  plant_ac_generated_topic: str
  grid_reactive_topic: str
  grid_export_topic: str