name: "CCT SCADA"
version: "0.0.42"
slug: "cct_dp3_scada"
description: "Home Assistant add-on CoCT DNP3"
url: "https://github.com/Voyanti/dnp3-scadat-test"
init: false
arch:
  - amd64
  - armv7
  - aarch64
startup: services
boot: auto
host_network: true

options:
  server: "vpn.example.com"
  OUTSTATION_ADDR: 101
  LISTEN_IP: "0.0.0.0"
  event_buffer_size: 20

  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: mqtt-user
  mqtt_password: mqtt-user
  mqtt_base_topic: "scada"

  plant_ac_generated_topic: "modbus/SungrowLogger/total_active_power/state"
  plant_ac_generated_watts_per_unit: 1
  grid_reactive_topic: "modbus/SungrowMeter/reactive_power/state"
  grid_reactive_var_per_unit: 1000
  grid_export_topic: "modbus/SungrowMeter/active_power/state"
  grid_export_watts_per_unit: 
  
  plant_active_power_set_topics: 
    - topic: modbus/SG1/power_limitation_setting/set
    - topic: modbus/SG2/power_limitation_setting/set
    - topic: modbus/SG3/power_limitation_setting/set
  plant_ramp_up_set_topic: "test/ramp_up/set"
  plant_ramp_down_set_topic: "test/ramp_down/set"
  
  max_total_nominal_active_power_kw: 375

schema:
  server: str
  OUTSTATION_ADDR: int
  LISTEN_IP: str
  event_buffer_size: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
  mqtt_base_topic: str
  plant_ac_generated_topic: str
  plant_ac_generated_watts_per_unit: float
  grid_reactive_topic: str
  grid_reactive_var_per_unit: float
  grid_export_topic: str
  grid_export_watts_per_unit: float
  plant_active_power_set_topics:
    - topic: str
  plant_ramp_up_set_topic: str
  plant_ramp_down_set_topic: str
  max_total_nominal_active_power_kw: float(90,1010)